version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/candilib
    networks:
      - candilib-network
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    networks:
      - candilib-network
volumes:
  dbdata:
networks:
  candilib-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
