version: '3.4'
services:
  web:
    image: candilib_web:${APP_VERSION:-latest}
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    env_file:
      - ${cnf:-.env}
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL:-mongodb://db:27017/candilib}
    networks:
      - candilib-network
  db:
    image: mongo:latest
    volumes:
      - ${DBDATA}/db:/data/db
    networks:
      - candilib-network
networks:
  candilib-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
