version: '3.4'
services:
  web:
    image: candilib_web:${APP_VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
      args:
          proxy: ${http_proxy}
          npm_registry: ${NPM_REGISTRY}
          no_proxy: ${no_proxy}
    container_name: candilib_web
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/candilib
    networks:
      - candilib-network
  db:
    image: mongo:latest
    container_name: candilib_db
    volumes:
      - dbdata:/data/db
    networks:
      - candilib-network
volumes:
  dbdata:
networks:
  candilib-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
