version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
      args: 
          proxy: ${http_proxy}
          npm_registry: ${NPM_REGISTRY}
          no_proxy: ${no_proxy} 
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-8000}:8000"
      - "9229:9229"
    volumes:
      - ./client:/usr/src/app/client
      - ./Intl:/usr/src/app/Intl
      - ./server:/usr/src/app/server
      - ./.babelrc:/usr/src/app/.babelrc
      - ./index.js:/usr/src/app/index.js
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./webpack.config.babel.js:/usr/src/app/webpack.config.babel.js
      - ./webpack.config.dev.js:/usr/src/app/webpack.config.dev.js
      - ./webpack.config.prod.js:/usr/src/app/webpack.config.prod.js
      - ./webpack.config.server.js:/usr/src/app/webpack.config.server.js
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/candilib
    stdin_open: true
    tty: true
    command: ./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0 index.js

  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
    ports:
      - "${WEB_PORT:-27017}:27017"
volumes:
  dbdata:
