version: '3.4'
services:
  front:
    image: candilib_web:${APP_VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile.front
      args:
          proxy: ${http_proxy}
          no_proxy: ${no_proxy}
          npm_registry: ${NPM_REGISTRY}
    container_name: candilib_web
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      NODE_ENV: production
